from typing import Any, Dict

"""Type stub for agent memory interface."""

class AgentMemoryInterface:
    """Interface for agent memory management."""

    def __init__(self, agent_id: str, agent_type: str) -> None: ...
    def get_project_context(self) -> Dict[str, Any]: ...
    def record_project_memory(self, category: str, content: str) -> None: ...
    def record_agent_memory(self, action: str, result: str) -> None: ...
