name: TeamCoach
version: 1.0.0
description: Auto-analyzes sessions and provides continuous improvement coaching

capabilities:
  - session_analysis
  - improvement_identification
  - github_issue_creation
  - performance_tracking
  - pattern_learning
  - coaching_reports

triggers:
  - event: session_completed
    action: analyze_session

  - event: pr_merged
    action: track_success_patterns

  - event: test_failure
    action: identify_test_improvements

  - event: error_logged
    action: analyze_error_patterns

metrics:
  session_metrics:
    - task_completion_rate
    - average_task_time
    - error_frequency
    - test_pass_rate
    - code_quality_score

  performance_metrics:
    - velocity_trend
    - quality_trend
    - efficiency_trend
    - learning_curve

improvement_categories:
  process:
    - workflow_optimization
    - task_decomposition
    - parallel_execution

  tooling:
    - agent_improvements
    - automation_opportunities
    - integration_enhancements

  documentation:
    - missing_documentation
    - outdated_guides
    - unclear_instructions

  quality:
    - test_coverage
    - code_review_findings
    - type_safety_issues

github_integration:
  issue_templates:
    improvement:
      title: "[TeamCoach] {title}"
      body: |
        ## Improvement Opportunity

        **Type**: {type}
        **Priority**: {priority}
        **Estimated Impact**: {impact}

        ## Description
        {description}

        ## Implementation Steps
        {steps}

        ## Related Sessions
        {sessions}

        ---
        *Generated by TeamCoach Agent*

      labels:
        - enhancement
        - TeamCoach
        - continuous-improvement

configuration:
  analysis_thresholds:
    performance_score_warning: 0.6
    error_rate_threshold: 5
    test_failure_threshold: 1

  coaching_priorities:
    critical_issues:
      - no_tasks_completed
      - high_error_rate
      - test_failures

    improvement_areas:
      - performance_optimization
      - quality_enhancement
      - process_refinement

  learning_parameters:
    min_sessions_for_patterns: 5
    success_threshold: 0.8
    failure_threshold: 0.4
    trend_analysis_window: 10

integration:
  base_agent: IntegratedAgent
  required_modules:
    - performance_analytics
    - capability_assessment
    - coaching_engine
    - github_client

  event_handlers:
    session_completed: analyze_and_coach
    pr_merged: update_success_patterns
    test_failure: generate_quality_improvements
    error_logged: analyze_error_patterns

security:
  safe_operations:
    - read_session_data
    - analyze_metrics
    - generate_reports
    - create_github_issues

  restricted_operations:
    - direct_code_modification
    - system_configuration_changes
    - sensitive_data_access
