from typing import Any, Callable, List, Optional, Tuple

class GadugiError(Exception): ...
class RecoverableError(GadugiError): ...
class NonRecoverableError(GadugiError): ...
class ErrorSeverity: ...
class RetryStrategy: ...

def retry(
    max_attempts: int = ...,
    initial_delay: float = ...,
    strategy: RetryStrategy = ...,
    backoff_factor: float = ...,
    exceptions: Tuple[type[Exception], ...] = ...,
    on_retry: Optional[Callable[..., Any]] = ...,
) -> Callable[..., Any]: ...
def graceful_degradation(
    fallback_value: Any = ...,
    log_errors: bool = ...,
    exceptions: Tuple[type[Exception], ...] = ...,
) -> Callable[..., Any]: ...

class ErrorHandler: ...
class CircuitBreaker: ...
class ErrorContext: ...

__all__: List[str] = []
