from typing import Any, Dict, List, Optional

# Core public classes / functions surfaced to callers
class XpiaDefense: ...
class XpiaDefenseConfig: ...
class XpiaDefenseResult: ...

def run_defense(
    payload: Dict[str, Any], config: Optional[XpiaDefenseConfig] = ...
) -> XpiaDefenseResult: ...
def evaluate_threat_level(result: XpiaDefenseResult) -> str: ...

__all__: List[str] = []
