version: '3.8'

services:
  neo4j:
    image: neo4j:5.12-community
    container_name: gadugi-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7475:7474"  # Alternative HTTP (per spec)
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/gadugi123!
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=2g
      - NEO4J_server_memory_pagecache__size=512m
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4JLABS_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
      - ./init:/var/lib/neo4j/import/init
    networks:
      - gadugi_network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:7474"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  gadugi_network:
    driver: bridge